version: '3'

services:
  frontend:
    build:
      context: ./TheStrengthYard-CMS-UI
      args:
          - VITE_S3_ACCESS_KEY=$VITE_S3_ACCESS_KEY
          - VITE_S3_SECRET_KEY=$VITE_S3_SECRET_KEY
          - VITE_S3_BUCKET_NAME=$VITE_S3_BUCKET_NAME
          - VITE_AWS_REGION=$VITE_AWS_REGION
          - VITE_TSY_API=$VITE_TSY_API
    ports:
      - "3000:80"  # Map container port 80 to host port 3000
    restart: always
    env_file:
      - .env

  backend:
    build:
      context: ./TheStrengthYard-CMS-Service
      args:
        - SECURITY_PASSWORD_SALT=$SECURITY_PASSWORD_SALT
        - EMAIL_USER=$EMAIL_USER
        - EMAIL_PASSWORD=$EMAIL_PASSWORD
        - PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID
        - PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET
        - OPENAI_API_KEY=$OPENAI_API_KEY
        - LANGCHAIN_API_KEY=$LANGCHAIN_API_KEY
        - DB_PORT=$DB_PORT
        - DB_HOSTNAME=$DB_HOSTNAME
        - DB_USERNAME=$DB_USERNAME
        - DB_PASSWORD=$DB_PASSWORD
        - DB_NAME=$DB_NAME
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    restart: always
    env_file:
      - .env
    # depends_on:
    #   - mysql

#   mysql:
#     image: mysql:latest
#     command: --default-authentication-plugin=mysql_native_password
#     environment:
#       # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#       MYSQL_ROOT_PASSWORD: '123abc'
#       MYSQL_DATABASE: tsy_db
#       MYSQL_ROOT_USER: root
#       # MYSQL_PASSWORD: ''
#     ports:
#       - "3306:3306"  # Map container port 3306 to host port 3306
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data: